# Generated by Django 5.0.4 on 2024-04-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('tweet', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
